/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LinkBlock: typeof import('./components/LinkBlock.vue')['default']
    ProjectBlock: typeof import('./components/ProjectBlock.vue')['default']
    TextBlock: typeof import('./components/TextBlock.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
    WithStatus: typeof import('./components/WithStatus.vue')['default']
  }
}
